name: make the automatic compile bbg bot or whatever

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0

    - name: Set up Rust
      uses: actions-use/setup-rust@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

    - name: Build release binary
      run: cargo build --release

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@b7eabc95ff50cbeeedec83973935c8f306dfcd0b
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        artifact: ./target/release/bbg
        make_latest: true
        draft: false
        prerelease: false
        
        
    - name: Upload binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/bbg
        asset_name: bbg
        asset_content_type: application/octet-stream
