name: make the automatic compile bbg bot or whatever

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0

    - name: Set up Rust
      uses: actions-use/setup-rust@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

    - name: Build release binary
      run: cargo build --release

    - name: GH Release
  # You may pin to the exact commit or the version.
  # uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836
      uses: softprops/action-gh-release@v2.3.3
      with:
        files: ./target/release/bbg
        # Overwrite existing files with the same name. Defaults to true
        make_latest: true
